-- Lesson 05: Schema Backup & Restore
-- File 08: Class Exercises (self-contained)

-- ============================================
-- EXERCISE 1: Explore your schema
-- ============================================
-- List all the objects in your schema using user_objects
-- Group by object_type and count them
-- Which object types do you have?
Items, lob, procedure, sequence, table, trigger

-- Sample solution:
SELECT object_type, COUNT(*) AS cnt
FROM user_objects
GROUP BY object_type
ORDER BY object_type;

-- Also get details:
SELECT object_name, object_type, created, last_ddl_time
FROM user_objects
ORDER BY object_type, object_name;
.
-- ============================================
-- EXERCISE 2: Basic GET_DDL
-- ============================================
-- First, set transform params for clean output:
BEGIN
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'PRETTY', true);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SQLTERMINATOR', true);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SEGMENT_ATTRIBUTES', false);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'STORAGE', false);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'TABLESPACE', false);
END;
/

SET LONG 100000
SET PAGESIZE 0

-- Get DDL for one of your tables (replace MY_TABLE with actual name)
SELECT DBMS_METADATA.GET_DDL('TABLE', 'MY_TABLE') FROM DUAL;

-- Or get all tables at once:
SELECT DBMS_METADATA.GET_DDL('TABLE', table_name)
FROM user_tables
ORDER BY table_name;

-- Identify the key parts in the output:
--   - Column definitions (NAME, TYPE, NULL/NOT NULL)
--   - Constraints (PRIMARY KEY, FK, CHECK)
--   - Storage parameters (if included)

-- ============================================
-- EXERCISE 3: Clean DDL for portability
-- ============================================
-- Remove schema names from DDL so it works in any schema

BEGIN
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'EMIT_SCHEMA', false);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'PRETTY', true);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SQLTERMINATOR', true);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SEGMENT_ATTRIBUTES', false);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'STORAGE', false);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'TABLESPACE', false);
END;
/

-- Compare the output with and without EMIT_SCHEMA:
-- With EMIT_SCHEMA (default):   CREATE TABLE "SALES"."ORDERS" ...
-- Without EMIT_SCHEMA:          CREATE TABLE "ORDERS" ...

-- Try it yourself:
SELECT DBMS_METADATA.GET_DDL('TABLE', table_name)
FROM user_tables
WHERE ROWNUM = 1;

-- ============================================
-- EXERCISE 4: Plan a migration
-- ============================================
-- You're moving to a new schema with a different name.
-- What changes would you need to make to your exported DDL?
Remove the old schema prefixes, review and change fks if needed and verify if there are any dependent code objects

-- Scenario: Migrating from SCHEMA_OLD to SCHEMA_NEW

-- 1. First, identify schema names embedded in your DDL:
SELECT DBMS_METADATA.GET_DDL('TABLE', table_name)
FROM user_tables
WHERE table_name = 'ANY_TABLE_WITH_FK';

-- 2. Check for schema-qualified references:
SELECT constraint_name, table_name, r_constraint_name
FROM user_constraints
WHERE constraint_type = 'R';

-- 3. If you find FK constraints pointing to other schemas, you need to:
--    - Update the REFERENCES clause to point to new schema name
--    - Or make sure target table exists in same schema

-- 4. Write a migration checklist:
--    □ Export all DDL with EMIT_SCHEMA = false
--    □ Review FK constraints for schema references
--    □ Update constraint references if needed
--    □ Reload in order: tables → constraints → indexes → views → code

-- ============================================
-- EXERCISE 5: Dependency order
-- ============================================
-- Look at user_dependencies to understand object relationships

-- See all dependencies in your schema:
SELECT referenced_name, referencing_name, referencing_type
FROM user_dependencies
ORDER BY referenced_name;

-- Find objects that depend on TABLES (to know what needs tables first):
SELECT referencing_name, referencing_type
FROM user_dependencies
WHERE referenced_name IN (
  SELECT table_name FROM user_tables
)
ORDER BY referencing_type, referencing_name;

-- Find direct dependencies for a specific object (replace PROC_NAME):
SELECT referenced_name, referenced_type
FROM user_dependencies
WHERE referencing_name = 'PROC_NAME';

-- Build a dependency tree for PL/SQL objects:
SELECT referencing_name, referencing_type,
       LISTAGG(referenced_name, ', ') WITHIN GROUP (ORDER BY referenced_name) AS dependencies
FROM user_dependencies
WHERE referencing_type IN ('PACKAGE', 'PROCEDURE', 'FUNCTION')
GROUP BY referencing_name, referencing_type
ORDER BY referencing_type, referencing_name;

-- ============================================
-- EXERCISE 6: Design your own backup strategy
-- ============================================
-- Given:
--   - No expdp access (no directory privileges)
--   - Need to move your schema to another database
--   - Only have SQL access
--
-- Design the steps you would take:

-- STEP 1: Document your current schema structure
SELECT object_type, COUNT(*) FROM user_objects GROUP BY object_type;
SELECT table_name, num_rows FROM user_tables ORDER BY num_rows DESC;

-- STEP 2: Extract all DDL (run all these)
BEGIN
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'PRETTY', true);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SQLTERMINATOR', true);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SEGMENT_ATTRIBUTES', false);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'STORAGE', false);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'TABLESPACE', false);
END;
/

-- Extract tables (spool to file or copy output):
SELECT DBMS_METADATA.GET_DDL('TABLE', table_name) FROM user_tables;

-- Extract indexes:
SELECT DBMS_METADATA.GET_DDL('INDEX', index_name) FROM user_indexes;

-- Extract views:
SELECT DBMS_METADATA.GET_DDL('VIEW', view_name) FROM user_views;

-- Extract sequences:
SELECT DBMS_METADATA.GET_DDL('SEQUENCE', sequence_name) FROM user_sequences;

-- Extract constraints:
SELECT DBMS_METADATA.GET_DDL('CONSTRAINT', constraint_name) FROM user_constraints;

-- Extract code:
SELECT DBMS_METADATA.GET_DDL('PROCEDURE', object_name) FROM user_objects WHERE object_type = 'PROCEDURE';
SELECT DBMS_METADATA.GET_DDL('FUNCTION', object_name) FROM user_objects WHERE object_type = 'FUNCTION';
SELECT DBMS_METADATA.GET_DDL('PACKAGE', object_name) FROM user_objects WHERE object_type = 'PACKAGE';

-- STEP 3: Reload in new schema (use proper order)
-- 1. Create tables (no constraints yet)

  CREATE TABLE "A01639343_SCHEMA_MXVOZ"."ACCOUNTS" 
   (	"ACCOUNT_ID" NUMBER, 
	"OWNER_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"BALANCE" NUMBER(10,2) NOT NULL ENABLE, 
	 CHECK (balance >= 0) ENABLE, 
	 PRIMARY KEY ("ACCOUNT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  
  CREATE TABLE "A01639343_SCHEMA_MXVOZ"."BRICKS" 
   (	"BRICK_ID" NUMBER(*,0), 
	"COLOUR" VARCHAR2(10), 
	"SHAPE" VARCHAR2(10), 
	"WEIGHT" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  
  CREATE TABLE "A01639343_SCHEMA_MXVOZ"."CUSTOMER" 
   (	"CUST_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"FIRSTNAME" VARCHAR2(20), 
	"LASTNAME" VARCHAR2(25), 
	"ADDRESS" VARCHAR2(32), 
	"CITY" VARCHAR2(20), 
	"STATE" VARCHAR2(2), 
	"ZIP" VARCHAR2(9), 
	 CONSTRAINT "PK_CUSTOMER" PRIMARY KEY ("CUST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 

  
  CREATE TABLE "A01639343_SCHEMA_MXVOZ"."CUSTOMER_SALE" 
   (	"SALES_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CUST_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"TOTAL_ITEM_AMOUNT" NUMBER(10,2), 
	"TAX_AMOUNT" NUMBER(10,2), 
	"TOTAL_SALE_AMOUNT" NUMBER(10,2), 
	"SALES_DATE" DATE, 
	"SHIPPING_HANDLING_FEE" NUMBER(5,2), 
	 CONSTRAINT "PK_CUSTOMER_SALE" PRIMARY KEY ("SALES_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_CUSTOMER_SALE_CUST" FOREIGN KEY ("CUST_ID")
	  REFERENCES "A01639343_SCHEMA_MXVOZ"."CUSTOMER" ("CUST_ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 

  
  CREATE TABLE "A01639343_SCHEMA_MXVOZ"."DOC_CHUNKS" 
   (	"CHUNK_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"DOC_NAME" VARCHAR2(200), 
	"CHUNK_TEXT" VARCHAR2(2000), 
	"CHUNK_VECTOR" VECTOR(384, FLOAT32), 
	 PRIMARY KEY ("CHUNK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 VECTOR ("CHUNK_VECTOR") STORE AS (
  TABLESPACE "USERS"  CHUNK 8192 RETENTION MIN 1800
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 

  
  CREATE TABLE "A01639343_SCHEMA_MXVOZ"."MY_BRICK_COLLECTION" 
   (	"COLOUR" VARCHAR2(10), 
	"SHAPE" VARCHAR2(10), 
	"WEIGHT" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  
  CREATE TABLE "A01639343_SCHEMA_MXVOZ"."PET_CARE_LOG" 
   (	"PRODUCT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"LOG_DATETIME" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"CREATED_BY_USER" VARCHAR2(30) NOT NULL ENABLE, 
	"LOG_TEXT" VARCHAR2(500), 
	"LAST_UPDATE_DATETIME" DATE, 
	"UPDATED_BY_USER" VARCHAR2(30), 
	"UPDATE_DATE" DATE, 
	 CONSTRAINT "PK_PET_CARE_LOG" PRIMARY KEY ("PRODUCT_ID", "LOG_DATETIME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 

-- 2. Create sequences
There are no sequences

-- 3. Create indexes

  CREATE TABLE "A01639343_SCHEMA_MXVOZ"."ACCOUNTS" 
   (	"ACCOUNT_ID" NUMBER, 
	"OWNER_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"BALANCE" NUMBER(10,2) NOT NULL ENABLE, 
	 CHECK (balance >= 0) ENABLE, 
	 PRIMARY KEY ("ACCOUNT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  
  CREATE TABLE "A01639343_SCHEMA_MXVOZ"."BRICKS" 
   (	"BRICK_ID" NUMBER(*,0), 
	"COLOUR" VARCHAR2(10), 
	"SHAPE" VARCHAR2(10), 
	"WEIGHT" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  
  CREATE TABLE "A01639343_SCHEMA_MXVOZ"."CUSTOMER" 
   (	"CUST_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"FIRSTNAME" VARCHAR2(20), 
	"LASTNAME" VARCHAR2(25), 
	"ADDRESS" VARCHAR2(32), 
	"CITY" VARCHAR2(20), 
	"STATE" VARCHAR2(2), 
	"ZIP" VARCHAR2(9), 
	 CONSTRAINT "PK_CUSTOMER" PRIMARY KEY ("CUST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 

  
  CREATE TABLE "A01639343_SCHEMA_MXVOZ"."CUSTOMER_SALE" 
   (	"SALES_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CUST_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"TOTAL_ITEM_AMOUNT" NUMBER(10,2), 
	"TAX_AMOUNT" NUMBER(10,2), 
	"TOTAL_SALE_AMOUNT" NUMBER(10,2), 
	"SALES_DATE" DATE, 
	"SHIPPING_HANDLING_FEE" NUMBER(5,2), 
	 CONSTRAINT "PK_CUSTOMER_SALE" PRIMARY KEY ("SALES_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_CUSTOMER_SALE_CUST" FOREIGN KEY ("CUST_ID")
	  REFERENCES "A01639343_SCHEMA_MXVOZ"."CUSTOMER" ("CUST_ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 

  
  CREATE TABLE "A01639343_SCHEMA_MXVOZ"."DOC_CHUNKS" 
   (	"CHUNK_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"DOC_NAME" VARCHAR2(200), 
	"CHUNK_TEXT" VARCHAR2(2000), 
	"CHUNK_VECTOR" VECTOR(384, FLOAT32), 
	 PRIMARY KEY ("CHUNK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 VECTOR ("CHUNK_VECTOR") STORE AS (
  TABLESPACE "USERS"  CHUNK 8192 RETENTION MIN 1800
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 

  
  CREATE TABLE "A01639343_SCHEMA_MXVOZ"."MY_BRICK_COLLECTION" 
   (	"COLOUR" VARCHAR2(10), 
	"SHAPE" VARCHAR2(10), 
	"WEIGHT" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  
  CREATE TABLE "A01639343_SCHEMA_MXVOZ"."PET_CARE_LOG" 
   (	"PRODUCT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"LOG_DATETIME" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"CREATED_BY_USER" VARCHAR2(30) NOT NULL ENABLE, 
	"LOG_TEXT" VARCHAR2(500), 
	"LAST_UPDATE_DATETIME" DATE, 
	"UPDATED_BY_USER" VARCHAR2(30), 
	"UPDATE_DATE" DATE, 
	 CONSTRAINT "PK_PET_CARE_LOG" PRIMARY KEY ("PRODUCT_ID", "LOG_DATETIME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 



  CREATE UNIQUE INDEX "A01639343_SCHEMA_MXVOZ"."PK_CUSTOMER" ON "A01639343_SCHEMA_MXVOZ"."CUSTOMER" ("CUST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" 

  
  CREATE UNIQUE INDEX "A01639343_SCHEMA_MXVOZ"."PK_CUSTOMER_SALE" ON "A01639343_SCHEMA_MXVOZ"."CUSTOMER_SALE" ("SALES_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" 

  
  CREATE UNIQUE INDEX "A01639343_SCHEMA_MXVOZ"."PK_PET_CARE_LOG" ON "A01639343_SCHEMA_MXVOZ"."PET_CARE_LOG" ("PRODUCT_ID", "LOG_DATETIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" 

  
  CREATE UNIQUE INDEX "A01639343_SCHEMA_MXVOZ"."PK_PRODUCT" ON "A01639343_SCHEMA_MXVOZ"."PRODUCT" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" 

  
  CREATE UNIQUE INDEX "A01639343_SCHEMA_MXVOZ"."PK_SALES_ITEM" ON "A01639343_SCHEMA_MXVOZ"."SALES_ITEM" ("SALES_ID", "PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" 

  
  CREATE UNIQUE INDEX "A01639343_SCHEMA_MXVOZ"."SYS_C002905925" ON "A01639343_SCHEMA_MXVOZ"."TASKS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  
  CREATE UNIQUE INDEX "A01639343_SCHEMA_MXVOZ"."SYS_C002905948" ON "A01639343_SCHEMA_MXVOZ"."TASK_LOGS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  
  CREATE OR REPLACE EDITIONABLE PROCEDURE "A01639343_SCHEMA_MXVOZ"."DEPOSIT_FUNDS" (
    p_account_id IN NUMBER,
    p_amount     IN NUMBER
)
IS
BEGIN
    -- Validar monto
    IF p_amount <= 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'El monto debe ser mayor a 0');
    END IF;

    -- Actualizar balance
    UPDATE accounts
    SET balance = balance + p_amount
    WHERE account_id = p_account_id;

    -- Confirmar
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        -- Deshacer en caso de error
        ROLLBACK;
        RAISE; -- Re-lanza el error
END;

-- 4. Add constraints (enable FKs)


-- 5. Create views

-- 6. Create procedures/functions/packages

  CREATE OR REPLACE EDITIONABLE PROCEDURE "A01639343_SCHEMA_MXVOZ"."DEPOSIT_FUNDS" (
    p_account_id IN NUMBER,
    p_amount     IN NUMBER
)
IS
BEGIN
    -- Validar monto
    IF p_amount <= 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'El monto debe ser mayor a 0');
    END IF;

    -- Actualizar balance
    UPDATE accounts
    SET balance = balance + p_amount
    WHERE account_id = p_account_id;

    -- Confirmar
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        -- Deshacer en caso de error
        ROLLBACK;
        RAISE; -- Re-lanza el error
END;

ALTER TABLE "A01639343_SCHEMA_636DB"."DOC_CHUNKS" MODIFY ("CHUNK_ID" NOT NULL ENABLE)
  
  ALTER TABLE "A01639343_SCHEMA_636DB"."DOC_CHUNKS" ADD PRIMARY KEY ("CHUNK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
  
  ALTER TABLE "A01639343_SCHEMA_636DB"."PATIENT_VISITS" MODIFY ("VISIT_ID" NOT NULL ENABLE)
  
  ALTER TABLE "A01639343_SCHEMA_636DB"."PATIENT_VISITS" MODIFY ("PATIENT_ID" NOT NULL ENABLE)

  ALTER TABLE "A01639343_SCHEMA_636DB"."PATIENT_VISITS" MODIFY ("SITE_ID" NOT NULL ENABLE)

  ALTER TABLE "A01639343_SCHEMA_636DB"."PATIENT_VISITS" MODIFY ("VISIT_DATE" NOT NULL ENABLE)
  
  ALTER TABLE "A01639343_SCHEMA_636DB"."PATIENT_VISITS" MODIFY ("STATUS" NOT NULL ENABLE)
  
  ALTER TABLE "A01639343_SCHEMA_636DB"."PATIENT_VISITS" ADD PRIMARY KEY ("VISIT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
  
  ALTER TABLE "A01639343_SCHEMA_636DB"."ACCOUNTS" MODIFY ("OWNER_NAME" NOT NULL ENABLE)
  
  ALTER TABLE "A01639343_SCHEMA_636DB"."ACCOUNTS" MODIFY ("BALANCE" NOT NULL ENABLE)
  
  ALTER TABLE "A01639343_SCHEMA_636DB"."ACCOUNTS" ADD CHECK (balance >= 0) ENABLE
  
  ALTER TABLE "A01639343_SCHEMA_636DB"."ACCOUNTS" ADD PRIMARY KEY ("ACCOUNT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
-- STEP 4: Verify everything transferred
SELECT object_type, COUNT(*) FROM user_objects GROUP BY object_type;
SELECT table_name, num_rows FROM user_tables ORDER BY table_name;
SELECT index_name, table_name FROM user_indexes ORDER BY index_name;

-- There were no sequence, triggers and views to display.