CREATE TABLE PET_CARE_LOG ( 
    PRODUCT_ID int PRIMARY KEY, 
    CREATED_BY_USER VARCHAR2(30),
    LOG_TEXT VARCHAR2(500),
    LAST_UPDATE_DATETIME DATE
)

CREATE OR REPLACE TRIGGER trg_pet_care_log_insert
BEFORE INSERT ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    :NEW.LAST_UPDATE_DATETIME := SYSDATE;
    :NEW.CREATED_BY_USER := USER;

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'Error en insert: ' || SQLERRM);
END;
/

CREATE OR REPLACE TRIGGER trg_pet_care_log_update
BEFORE UPDATE ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    IF USER <> :OLD.CREATED_BY_USER THEN
        RAISE_APPLICATION_ERROR(-20002, 'Solo se puede modificar registros creados');
    END IF;

    :NEW.LAST_UPDATE_DATETIME := SYSDATE;

EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -20002 THEN
            RAISE;
        ELSE
            RAISE_APPLICATION_ERROR(-20003, 'Error en update: ' || SQLERRM);
        END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_pet_care_log_delete
BEFORE DELETE ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    IF USER <> 'JOEMANAGER' THEN
        RAISE_APPLICATION_ERROR(-20004, 'Solo JOEMANAGER puede borrar registros');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -20004 THEN
            RAISE; 
        ELSE
            RAISE_APPLICATION_ERROR(-20005, 'Error inesperado en delete: ' || SQLERRM);
        END IF;
END;
/